site_name: Python-Starter
repo_url: https://github.com/SyntaxRules/python-starter/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - rust
nav:
    - 'Overview': 'index.md'
    - 'User Guide':
        - 'Quick Start': 'quick-start.md'
        - 'Installation Instructions': 'installation-instructions.md'
    - 'Classes':
        - 'Singly Linked List': 'lists/singly/linked_list.md'
        - 'Doubly Linked List': 'lists/doubly/linked_list.md'
    - 'License': 'license.md'
plugins:
    - search
    - mkdocstrings
markdown_extensions:
    - markdown_katex:
        no_inline_svg: True
        insert_fonts_css: True
        # macro-file: macros.tex
    - plantuml_markdown:
        server: 'http://www.plantuml.com/plantuml'
        format: svg